"""create abastecimentos

Revision ID: 63f77c080fc3
Revises: 
Create Date: 2025-12-19 14:22:46.498384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f77c080fc3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abastecimentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_posto', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tipo_combustivel', sa.Enum('GASOLINA', 'ETANOL', 'DIESEL', name='tipocombustivel'), nullable=False),
    sa.Column('preco_por_litro', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('volume_abastecido', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('cpf_motorista', sa.String(length=11), nullable=False),
    sa.Column('improper_data', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abastecimentos_cpf_motorista'), 'abastecimentos', ['cpf_motorista'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_abastecimentos_cpf_motorista'), table_name='abastecimentos')
    op.drop_table('abastecimentos')
    # ### end Alembic commands ###
